const INIT_TOMATO = 'TOMATO/INIT';
const ADD_TOMATO = 'TOMATO/ADD';
const TOGGLE_TOMATO = 'TOMATO/TOGGLE';
const REMOVE_TOMATO = 'TOMATO/REMOVE';
const UPDATE_TOMATO = 'TOMATO/UPDATE';


export {INIT_TOMATO,ADD_TOMATO,TOGGLE_TOMATO,REMOVE_TOMATO,UPDATE_TOMATO};