const INIT_TODO = 'TODO/INIT';
const ADD_TODO = 'TODO/ADD';
const TOGGLE_TODO = 'TODO/TOGGLE';
const REMOVE_TODO = 'TODO/REMOVE';
const MODIFY_TODO = 'TODO/MODIFY';
const ENABLE_EDIT_TODO = 'TODO/EDIT_ENABLE';


export {INIT_TODO,ADD_TODO,TOGGLE_TODO,REMOVE_TODO,MODIFY_TODO,ENABLE_EDIT_TODO};